/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication43;

import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author GANDHY
 */
public class PanelRopa extends javax.swing.JPanel {

    /**
     * Creates new form PanelRopa
     */
    public PanelRopa() {
        initComponents();
    }

    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public ButtonGroup getBtgRopa() {
        return btgRopa;
    }
    
    public ButtonGroup getBtgTalla() {
        return btgTalla;
    }

    public JRadioButton getRbCamisa() {
        return rbCamisa;
    }

    public JRadioButton getRbCamiseta() {
        return rbCamiseta;
    }

    public JRadioButton getRbChaqueta() {
        return rbChaqueta;
    }

    public JRadioButton getRbMedias() {
        return rbMedias;
    }

    public JRadioButton getRbPantalon() {
        return rbPantalon;
    }

    public JRadioButton getRbVestido() {
        return rbVestido;
    }

    public JRadioButton getRbZapatos() {
        return rbZapatos;
    }
    
    public String getTipoRopa() {
        if(rbCamisa.isSelected()){
           return rbCamisa.getText();
        }else if(rbCamiseta.isSelected()){
            return rbCamiseta.getText();
        }else if(rbChaqueta.isSelected()){
            return rbChaqueta.getText();
        }else if(rbMedias.isSelected()){
            return rbMedias.getText();
        }else if(rbPantalon.isSelected()){
            return rbPantalon.getText();
        }else if(rbPantalon.isSelected()){
            return rbPantalon.getText();
        }else if(rbVestido.isSelected()){
            return rbVestido.getText();
        }
        return "";
    }
    public int getTalla() {
        if(rb34.isSelected()){
           return Integer.parseInt(rb34.getText());
        }else if(rb36.isSelected()){
           return Integer.parseInt(rb36.getText());
        }else if(rb38.isSelected()){
           return Integer.parseInt(rb38.getText());
        }else if(rb40.isSelected()){
           return Integer.parseInt(rb40.getText());
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgRopa = new javax.swing.ButtonGroup();
        btgTalla = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbPantalon = new javax.swing.JRadioButton();
        rbCamiseta = new javax.swing.JRadioButton();
        rbCamisa = new javax.swing.JRadioButton();
        rbChaqueta = new javax.swing.JRadioButton();
        rbMedias = new javax.swing.JRadioButton();
        rbZapatos = new javax.swing.JRadioButton();
        rbVestido = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rb34 = new javax.swing.JRadioButton();
        rb36 = new javax.swing.JRadioButton();
        rb38 = new javax.swing.JRadioButton();
        rb40 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Ropa"));

        jLabel1.setText(" Seleccione producto:");

        jLabel2.setText("Cantidad:");

        btgRopa.add(rbPantalon);
        rbPantalon.setText("Pantalon");

        btgRopa.add(rbCamiseta);
        rbCamiseta.setText("Camiseta");

        btgRopa.add(rbCamisa);
        rbCamisa.setText("Camisa");

        btgRopa.add(rbChaqueta);
        rbChaqueta.setText("Chaqueta");

        btgRopa.add(rbMedias);
        rbMedias.setText("Medias");

        btgRopa.add(rbZapatos);
        rbZapatos.setText("Zapatos");

        btgRopa.add(rbVestido);
        rbVestido.setText("Vestido");

        jLabel3.setText("Talla:");

        btgTalla.add(rb34);
        rb34.setText("34");

        btgTalla.add(rb36);
        rb36.setText("36");

        btgTalla.add(rb38);
        rb38.setText("38");

        btgTalla.add(rb40);
        rb40.setText("40");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ropa.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPantalon)
                    .addComponent(rbCamisa)
                    .addComponent(rbMedias)
                    .addComponent(rbChaqueta)
                    .addComponent(jLabel1)
                    .addComponent(rbCamiseta)
                    .addComponent(rbZapatos)
                    .addComponent(rbVestido))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb34)
                            .addComponent(rb36)
                            .addComponent(rb38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb40))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbPantalon))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCamiseta))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCamisa)
                            .addComponent(rb34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbChaqueta)
                            .addComponent(rb36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMedias)
                            .addComponent(rb38)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb40)
                    .addComponent(rbZapatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVestido)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgRopa;
    private javax.swing.ButtonGroup btgTalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rb34;
    private javax.swing.JRadioButton rb36;
    private javax.swing.JRadioButton rb38;
    private javax.swing.JRadioButton rb40;
    private javax.swing.JRadioButton rbCamisa;
    private javax.swing.JRadioButton rbCamiseta;
    private javax.swing.JRadioButton rbChaqueta;
    private javax.swing.JRadioButton rbMedias;
    private javax.swing.JRadioButton rbPantalon;
    private javax.swing.JRadioButton rbVestido;
    private javax.swing.JRadioButton rbZapatos;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
