/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication43;

import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author GANDHY
 */
public class PanelTecnologia extends javax.swing.JPanel {

    /**
     * Creates new form PanelTecnología
     */
    public PanelTecnologia() {
        initComponents();
    }

    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public ButtonGroup getBtgTecno() {
        return btgTecno;
    }

    public JRadioButton getRbAudifonos() {
        return rbAudifonos;
    }

    public JRadioButton getRbCamara() {
        return rbCamara;
    }

    public JRadioButton getRbCelular() {
        return rbCelular;
    }

    public JRadioButton getRbComputadora() {
        return rbComputadora;
    }

    public JRadioButton getRbReloj() {
        return rbReloj;
    }

    public JRadioButton getRbTablet() {
        return rbTablet;
    }

    public JRadioButton getRbTelevision() {
        return rbTelevision;
    }
    
    public String getTipoTecno() {
        if(rbAudifonos.isSelected()){
           return rbAudifonos.getText();
        }else if(rbCamara.isSelected()){
            return rbCamara.getText();
        }else if(rbCelular.isSelected()){
            return rbCelular.getText();
        }else if(rbComputadora.isSelected()){
            return rbComputadora.getText();
        }else if(rbReloj.isSelected()){
            return rbReloj.getText();
        }else if(rbTablet.isSelected()){
            return rbTablet.getText();
        }else if(rbTelevision.isSelected()){
            return rbTelevision.getText();
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTecno = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbAudifonos = new javax.swing.JRadioButton();
        rbCelular = new javax.swing.JRadioButton();
        rbTablet = new javax.swing.JRadioButton();
        rbReloj = new javax.swing.JRadioButton();
        rbComputadora = new javax.swing.JRadioButton();
        rbTelevision = new javax.swing.JRadioButton();
        rbCamara = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tecnología"));

        jLabel1.setText(" Seleccione producto:");

        jLabel2.setText("Cantidad:");

        btgTecno.add(rbAudifonos);
        rbAudifonos.setText("Audifonos");

        btgTecno.add(rbCelular);
        rbCelular.setText("Celular");

        btgTecno.add(rbTablet);
        rbTablet.setText("Tablet");

        btgTecno.add(rbReloj);
        rbReloj.setText("Reloj");

        btgTecno.add(rbComputadora);
        rbComputadora.setText("Computadora");

        btgTecno.add(rbTelevision);
        rbTelevision.setText("Television");

        btgTecno.add(rbCamara);
        rbCamara.setText("Camara");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tecnologia.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCelular)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbTelevision)
                                .addComponent(rbCamara))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbAudifonos)
                                .addComponent(rbTablet)
                                .addComponent(rbComputadora)
                                .addComponent(rbReloj)
                                .addComponent(jLabel1))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAudifonos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTablet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbReloj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbComputadora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTelevision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCamara))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTecno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbAudifonos;
    private javax.swing.JRadioButton rbCamara;
    private javax.swing.JRadioButton rbCelular;
    private javax.swing.JRadioButton rbComputadora;
    private javax.swing.JRadioButton rbReloj;
    private javax.swing.JRadioButton rbTablet;
    private javax.swing.JRadioButton rbTelevision;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
