/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication43;

import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author GANDHY
 */
public class PanelComida extends javax.swing.JPanel {

    /**
     * Creates new form PanelComida
     */
    public PanelComida() {
        initComponents();
    }

    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public JRadioButton getRbHamburguesa() {
        return rbHamburguesa;
    }

    public JRadioButton getRbHelado() {
        return rbHelado;
    }

    public JRadioButton getRbHotDog() {
        return rbHotDog;
    }

    public JRadioButton getRbPastel() {
        return rbPastel;
    }

    public JRadioButton getRbPizza() {
        return rbPizza;
    }

    public JRadioButton getRbPolloFrito() {
        return rbPolloFrito;
    }

    public JRadioButton getRbTacos() {
        return rbTacos;
    }
    
    public String getTipoComida() {
        if(rbHamburguesa.isSelected()){
           return rbHamburguesa.getText();
        }else if(rbHelado.isSelected()){
            return rbHelado.getText();
        }else if(rbHotDog.isSelected()){
            return rbHotDog.getText();
        }else if(rbPastel.isSelected()){
            return rbPastel.getText();
        }else if(rbPizza.isSelected()){
            return rbPizza.getText();
        }else if(rbPolloFrito.isSelected()){
            return rbPolloFrito.getText();
        }else if(rbTacos.isSelected()){
            return rbTacos.getText();
        }
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgComida = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbPizza = new javax.swing.JRadioButton();
        rbHamburguesa = new javax.swing.JRadioButton();
        rbHotDog = new javax.swing.JRadioButton();
        rbTacos = new javax.swing.JRadioButton();
        rbPolloFrito = new javax.swing.JRadioButton();
        rbHelado = new javax.swing.JRadioButton();
        rbPastel = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Comida"));

        jLabel1.setText(" Seleccione producto:");

        jLabel2.setText("Cantidad:");

        btgComida.add(rbPizza);
        rbPizza.setText("Pizza");

        btgComida.add(rbHamburguesa);
        rbHamburguesa.setText("Hamburguesa");

        btgComida.add(rbHotDog);
        rbHotDog.setText("Hot-Dog");

        btgComida.add(rbTacos);
        rbTacos.setText("Tacos");

        btgComida.add(rbPolloFrito);
        rbPolloFrito.setText("Pollo-Frito");
        rbPolloFrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPolloFritoActionPerformed(evt);
            }
        });

        btgComida.add(rbHelado);
        rbHelado.setText("Helado");

        btgComida.add(rbPastel);
        rbPastel.setText("Pastel");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comida.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbHamburguesa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbHelado)
                                .addComponent(rbPastel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbPizza)
                                .addComponent(rbHotDog)
                                .addComponent(rbPolloFrito)
                                .addComponent(rbTacos)
                                .addComponent(jLabel1))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPizza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbHamburguesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbHotDog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbTacos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPolloFrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbHelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPastel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbPolloFritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPolloFritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPolloFritoActionPerformed

    public ButtonGroup getBtgComida() {
        return btgComida;
    }

    public void setBtgComida(ButtonGroup btgComida) {
        this.btgComida = btgComida;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbHamburguesa;
    private javax.swing.JRadioButton rbHelado;
    private javax.swing.JRadioButton rbHotDog;
    private javax.swing.JRadioButton rbPastel;
    private javax.swing.JRadioButton rbPizza;
    private javax.swing.JRadioButton rbPolloFrito;
    private javax.swing.JRadioButton rbTacos;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
