/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication43;

import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author GANDHY
 */
public class PanelCategoria extends javax.swing.JPanel {
    /**
     * Creates new form PanelCategoria
     */
    public PanelCategoria() {
        initComponents();
    }

    public JRadioButton getRbComida() {
        return rbComida;
    }

    public JRadioButton getRbRopa() {
        return rbRopa;
    }

    public JRadioButton getRbTecnologia() {
        return rbTecnologia;
    }

    public ButtonGroup getButtonGroupCategoria() {
        return buttonGroupCategoria;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCategoria = new javax.swing.ButtonGroup();
        rbTecnologia = new javax.swing.JRadioButton();
        rbRopa = new javax.swing.JRadioButton();
        rbComida = new javax.swing.JRadioButton();
        lblSeleccionCategoria = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        buttonGroupCategoria.add(rbTecnologia);
        rbTecnologia.setText("Tecnología");

        buttonGroupCategoria.add(rbRopa);
        rbRopa.setText("Ropa");

        buttonGroupCategoria.add(rbComida);
        rbComida.setText("Comida");

        lblSeleccionCategoria.setText("Seleccione categoria");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbComida)
                            .addComponent(rbRopa)
                            .addComponent(rbTecnologia))
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblSeleccionCategoria)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeleccionCategoria)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbComida)
                        .addGap(18, 18, 18)
                        .addComponent(rbRopa)
                        .addGap(18, 18, 18)
                        .addComponent(rbTecnologia)
                        .addGap(16, 16, 16)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSeleccionCategoria;
    private javax.swing.JRadioButton rbComida;
    private javax.swing.JRadioButton rbRopa;
    private javax.swing.JRadioButton rbTecnologia;
    // End of variables declaration//GEN-END:variables
}
